spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mail.MailSenderAutoConfiguration
      - org.springframework.boot.autoconfigure.mail.MailSenderValidatorAutoConfiguration
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:nandhas_ecommerce}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:2395}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false

app:
  storage:
    type: ${STORAGE_TYPE:s3}
  aws:
    s3:
      bucket-name: ${AWS_S3_BUCKET:nandhas-media-bucket}
      region: ${AWS_REGION:ap-south-2}
      cloudfront-domain: ${AWS_CLOUDFRONT_DOMAIN:d123456abcdef8.cloudfront.net}

logging:
  level:
    com.company.app: INFO
