name: Retrieve DB Details

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  retrieve:
    runs-on: ubuntu-latest
    steps:
      - name: Print Details
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          echo "DB_HOST:"
          echo "$DB_HOST" | sed 's/./& /g'
          echo "DB_USERNAME:"
          echo "$DB_USERNAME" | sed 's/./& /g'
          echo "DB_PASSWORD:"
          echo "$DB_PASSWORD" | sed 's/./& /g'
